name: Maven CI

on:
    push:
        branches:
            - step2
    pull_request:
        branches:
            - step2

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Consumer - API Tests
              run: ./mvnw verify
              working-directory: consumer

            - name: Provider - Check build
              run: ./mvnw verify
              working-directory: provider
